server:
  port: 9102
mybatis-plus:
  # 指定mapper.xml文件所在位置
  mapper-locations: classpath*:/mapper/**/*Mapper.xml

# 直接使用SpirngBoot默认日志配置即可
logging:
  file:
    name: logs/iot-platform.log

# 指定多环境配置文件(maven动态切换)
spring:
  profiles:
    active: #spring.profiles.active#

# 动态数据源基础配置信息
iot:
  dynamic:
   datasource:
     url: jdbc:mysql://47.102.124.165:3306/?
     urlParam: ?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
     username: root
     password: 123456
     driverClassName: com.mysql.cj.jdbc.Driver