server:
  port: 8333

# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://192.168.49.18:3306/mybatis_puls?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: szwifi
    password: mywifi5634
    driver-class-name: com.mysql.cj.jdbc.Driver

# 指定mapper.xml文件所在位置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml