server:
  port: 8333

# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://47.102.124.165:3306/mybatis_puls?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  # 指定mapper.xml文件所在位置
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  # spring boot集成mybatis的方式打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  file:
    name: log/springboot-mybatisplus-mysql.log
