# 开发环境下的公共配置放在这个文件中
# DataSource Config
spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: root
          password: root
          url: jdbc:mysql://47.102.124.165:3306/dynamic-master?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
          # 加上这个属性，就相当于有了连接池了哦
          hikari:
            max-pool-size: 100
