# 配置文件上传路径
apihu-file-path:
    linux: /home/keqi/myApp/
    windows: E:/apihu-upload-file/

# 开启 knife4j 增强功能
knife4j:
    enable: true
    basic:
        enable: false
        username: admin
        password: 123456

# 配置日志文件
logging:
    file:
        name: logs/apihu.log
    level:
        com:
            keqi: debug

# 配置 MyBatisPlus 日志和别名包
mybatis-plus:
    config-location:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        type-aliases-package: com.keqi.apihu.core.typeHandler

# 配置端口号和应用路径
server:
    port: 9090
    servlet:
        context-path: /apihu

# 配置数据源信息
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123456
        url: jdbc:mysql://120.25.26.123:3306/apihu?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
        username: root
    servlet:
        multipart:
            max-file-size: 20MB
            max-request-size: 30MB