# spring:
  # mvc:
    # 静态资源的全局映射路径默认是 ip:port/context-path/**，但是可以通过此配置给静态资源路径映射添加统一前缀
    # static-path-pattern: /res
  # resources:
    # 此属性对应的配置类中默认配置了 4 个静态资源映射路径，可以通过此属性重新进行配置，但是会覆盖默认的值，不建议这么干
    # static-locations: [ classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/ ]

# 以上两个配置都没有必要使用，知道这回事就行