spring:
  datasource:
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.102.124.165:3306/mapper_xml?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root

server:
  port: 9102

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**/*Mapper.xml

logging:
  file:
    name: logs/springboot-mybatis-mapper-xml.log
