server:
    port: 21304
    servlet:
        context-path: /grid

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Aliyun_rds_123456
        url: jdbc:mysql://rm-bp1f65ehm719kd63y5o.mysql.rds.aliyuncs.com:3306/047-grid-supervision?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
        username: keqi
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 120MB


logging:
    file:
        name: logs/app.log
    level:
        com:
            keqi: debug

mybatis:
    config-location:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

knife4j:
    enable: true
