server:
  port: 8333

# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://47.102.124.165:3306/mybatis_puls?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  # 指定mapper.xml文件所在位置
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  # mybatis打印sql(配合MyBatis Log Plugin插件可以在控制台查看格式化并且填充了占位符的SQL语句)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  file:
    name: logs/springboot-mybatisplus-mysql.log

swagger:
  title: SpringBoot整合knife4j
  description: SpringBoot整合knife4j
  version: 1.0
  terms-of-service-url: http://www.keqi.cn/
  base-package: com.keqi.springbootknife4j
