spring:
  datasource:
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.25.26.123:3306/ry-vue?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root

server:
  port: 8333

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  # 只有这样 typeHandler 中的类使用了 @Alias 注解才会生效
  type-aliases-package: com.keqi.springbootmybatistypehandler.typeHandler


