# 本机开发环境

# 配置数据源信息(此处使用了 p6spy 插件统计 SQL 执行时间，仅用于开发阶段)
spring:
    datasource:
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        password: 123456
        url: jdbc:p6spy:mysql://120.25.26.123:3306/knife4j?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
        username: root
    servlet:
        multipart:
            max-file-size: 20MB
            max-request-size: 30MB
    redis:
        url: redis://user:123456@120.25.26.123:6379


# 开启 knife4j 增强功能
knife4j:
    enable: true
    documents:
        -
            group: 接口文档
            name: 自定义文档
            # 某一个文件夹下所有的.md文件
            locations: classpath:markdown/*
    setting:
        enableSwaggerModels: false

# 配置日志文件
logging:
    file:
        name: logs/app.log
    level:
        com:
            keqi: debug

# 配置 MyBatisPlus 日志和别名包
mybatis-plus:
    config-location:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        type-aliases-package: com.keqi.seed.core.typeHandler

